In [26]:
# %%
import pandas as pd
import plotly.express as px

df = pd.read_excel('extract_constructions.xlsx', sheet_name='category_summary')
df

    verb level             category    n  total   pct
0   like    A1                 noun  631   1183  53.3
1   like    A1                 none  263   1183  22.2
2   like    A1              pronoun  144   1183  12.2
3   like    A1               gerund   51   1183   4.3
4   like    A1           infinitive   44   1183   3.7
..   ...   ...                  ...  ...    ...   ...
74  take   B1+      passive_subject   10    887   1.1
75  take   B1+              clausal    3    887   0.3
76  take   B1+           infinitive    3    887   0.3
77  take   B1+               gerund    1    887   0.1
78  take   B1+  predicate_adjective    1    887   0.1

[79 rows x 6 columns]

In [27]:
# %%
level_order = ['A1', 'A2', 'B1+']
category_order = ['noun', 'proper_noun', 'coordinated_noun', 'pronoun',
                   'gerund', 'infinitive', 'clausal', 'predicate_adjective',
                   'passive_subject', 'phrasal_only', 'none']
verb_order = ['take', 'make', 'like']

orders = {'level': level_order, 'category': category_order, 'verb': verb_order}

# %%
plot_df = df.copy()
plot_df['n_label'] = 'n=' + plot_df['n'].astype(str)

def plot_verb_panel(df, verb, exclude_none=False):
    sub = df[df['verb'] == verb]
    if exclude_none:
        sub = sub[sub['category'] != 'none']
    fig = px.line(
        sub, x='level', y='pct', facet_col='category', facet_col_wrap=5,
        category_orders=orders, markers=True, text='n_label',
        hover_data={'n': True, 'total': True},
        labels={'pct': '% of sentences', 'level': ''},
        title=f'{verb}: category share by CEFR level',
    )
    fig.update_traces(textposition='top center', textfont_size=9)
    fig.update_yaxes(matches=None, showticklabels=True, title='')
    fig.for_each_annotation(lambda a: a.update(text=a.text.split('=')[-1]))
    fig.update_layout(showlegend=False, height=450)
    return fig

# %%
plot_verb_panel(plot_df, 'take').show()
plot_verb_panel(plot_df, 'make').show()
plot_verb_panel(plot_df, 'like').show()

# No real clear patterns

# Noun collocations, these are the most frequent category by far
depending on CEFR level   
take: 70–72%   
make: 42–46%  
like: 52–54%

# "take"

In [28]:
raw = pd.read_excel('extract_constructions.xlsx', sheet_name='raw_all')

# %%
noun_df = pd.read_excel('extract_constructions.xlsx', sheet_name='noun_collocates')

def biggest_movers(noun_df, verb, top_n=15, min_pct=0.5):
    sub = noun_df[noun_df['verb'] == verb]
    wide = sub.pivot_table(index='noun', columns='level',
                            values='pct_of_sentences', fill_value=0)
    wide = wide.reindex(columns=['A1', 'A2', 'B1+'], fill_value=0)
    # ignore nouns too rare to be worth reading into either way
    wide = wide[wide.max(axis=1) >= min_pct]
    wide['delta_A1_A2'] = wide['A2'] - wide['A1']
    wide['delta_A2_B1'] = wide['B1+'] - wide['A2']
    wide['delta_A1_B1'] = wide['B1+'] - wide['A1']
    return wide.sort_values('delta_A1_B1', ascending=False)

# %%
movers = biggest_movers(noun_df, 'take')
print('Rising toward B1+ (top):')
print(movers.head(top_n=10) if False else movers.head(10))
print('\nReceding toward B1+ (bottom):')
print(movers.tail(10))

Rising toward B1+ (top):
level       A1   A2  B1+  delta_A1_A2  delta_A2_B1  delta_A1_B1
noun
part       2.5  5.4  6.4          2.9          1.0          3.9
time       0.7  3.3  3.3          2.6          0.0          2.6
place      0.0  1.7  1.7          1.7          0.0          1.7
things     0.4  2.2  2.0          1.8         -0.2          1.6
care       0.7  0.8  2.0          0.1          1.2          1.3
water      1.4  0.9  2.5         -0.5          1.6          1.1
foods      1.1  2.0  2.1          0.9          0.1          1.0
dog        0.7  1.4  1.5          0.7          0.1          0.8
coat       0.0  0.2  0.8          0.2          0.6          0.8
breakfast  1.4  0.5  2.1         -0.9          1.6          0.7

Receding toward B1+ (bottom):
level       A1   A2  B1+  delta_A1_A2  delta_A2_B1  delta_A1_B1
noun
bicycle    0.7  0.0  0.0         -0.7          0.0         -0.7
bus        0.7  0.2  0.0         -0.5         -0.2         -0.7
wallet     1.1  0.4  0.2         -0.7         -0.2         -0.9
picture    1.8  2.8  0.8          1.0         -2.0         -1.0
album      1.4  0.4  0.2         -1.0         -0.2         -1.2
glasses    1.4  0.6  0.2         -0.8         -0.4         -1.2
thing      2.2  1.0  1.0         -1.2          0.0         -1.2
pictures   4.0  3.1  2.7         -0.9         -0.4         -1.3
bankbook   6.9  3.5  0.3         -3.4         -3.2         -6.6
money     13.4  5.2  3.8         -8.2         -1.4         -9.6

In [29]:
# examples of take part A2
raw[(raw['verb']=='take') & (raw['level']=='A2') & (raw['collocate']=='part')]['sentence'].sample(10, random_state=42).to_list()

['After the festival, I took part in the.',
 'So we need more groups which take part in our school festival.',
 'But at last almost of our classmates took part in this idea.',
 "To say truth, I couldn't take part is this festival this year.",
 'I wonder why eneyerse took part in school festival.',
 'But I took part in it in last year and two years ago.',
 'I took part in the contest and I got the first prize.',
 "I'll have to take part in KWF the next year because I am a champion!",
 'I also took part in.',
 "This year, I didn't take part in my school festival."]

In [30]:
# examples of take time A2
raw[(raw['verb']=='take') & (raw['level']=='A2') & (raw['collocate']=='time')]['sentence'].sample(10, random_state=42).to_list()

['I also like rice and miso soup, but it takes a time to eat.',
 'I think that it takes time to cook rice and soup.',
 'When I had my parents buy it, it took long time to persuade them.',
 'Because it is not take much time to have bread.',
 'By the way, I want to eat rice better, but it takes rather more time.',
 'I like bread more than rice, for I have to take a long time to eat rice.',
 "so, our's breakfast is bread and, milk tea, Because, It takes not much time to make them.",
 'Becaus bread is takes time.',
 'People say it takes time to cook rice cooker I want to sleep.',
 'But, it takes long time, so I have to get up earlier.']

In [21]:
# examples of take place A2
raw[(raw['verb']=='take') & (raw['level']=='A2') & (raw['collocate']=='place')]['sentence'].sample(10, random_state=42).to_list()

['So there is a bankbook at taking easy place.',
 'I have gone to bed by 10:30 PM but I usually go to bed at 1:00AM, for Festival Komaba will take place on November 1st, 2nd, 3rd, and we must prepare it.',
 'I want to take place a next year too.',
 'Our school festival took place on 14th, 15th September.',
 'Our school festival took place on September.',
 'If the big earthquake took place, I would bring out my pet at first.',
 'So we took place.',
 'Our school festival which is named "[proper noun] Festival "took place at September 15th and 16th.',
 'Our school festival take place in 15 September.',
 'It is tradition which has been taken place for long time.']

In [31]:
# examples of take time B1+
raw[(raw['verb']=='take') & (raw['level']=='B1+') & (raw['collocate']=='time')]['sentence'].sample(2, random_state=42).to_list()

['Rice and miso soup take much time.',
 'But it takes more time to cook rice in The morning.']

In [32]:
# examples or take money
raw[(raw['verb']=='take') & (raw['level']=='A1') & (raw['collocate']=='money')]['sentence'].sample(10, random_state=42).to_list()

['I would take out money and bankbook first thing.',
 'I take money and food.',
 'I take money, .',
 'I will take out money.',
 'I will take out money and bank book first.',
 'He worked, and he take much money.',
 'I would take out my money.',
 'I will take money and album',
 "Don't take a many money, , I take a food and water and.",
 "But, toyears I couldn't take new years money."]

# % of collocations by topic

In [33]:
# %%
def topic_distribution(raw_df, verb):
    sub = raw_df[raw_df['verb'] == verb]
    counts = sub.groupby(['level', 'topic']).size().reset_index(name='n')
    totals = sub.groupby('level').size().reset_index(name='total')
    dist = counts.merge(totals, on='level')
    dist['pct'] = (dist['n'] / dist['total'] * 100).round(1)
    wide = dist.pivot_table(index='topic', columns='level', values='pct', fill_value=0)
    wide = wide.reindex(columns=['A1', 'A2', 'B1+'], fill_value=0)
    return wide.sort_values('A1', ascending=False)

# %%
topic_distribution(raw, 'take')

level         A1    A2   B1+
topic
earthquake  67.1  63.3  59.0
urashima    11.2   6.0   7.4
festival    10.1  12.8  14.4
dream        4.7   3.7   5.7
otoshidama   3.6   4.6   2.3
breakfast    3.2   9.6  11.2

### Breakfast sentences

In [35]:
# %%
for lvl in ['A1', 'A2', 'B1+']:
    sub = raw[(raw['verb']=='take') & (raw['topic']=='breakfast') & (raw['level']==lvl) &
              raw['category'].isin(['noun', 'proper_noun'])]
    print(f'--- take / breakfast / {lvl} (n={len(sub)}) ---')
    for _, row in sub.iterrows():
        print(f"{row['collocate']:15s} {row['sentence']}")
    print()

--- take / breakfast / A1 (n=9) ---
days            Because I take that days.
time            "It's takes too much time.
minutes         It takes a few minutes.
breakfast       I do not take breakfast, because I get up late.
bread           I think it is foolish to take bread or rice always.
breakfast       Usually, I try to take a breakfast every morning.
breakfast       I always take a breakfast on weekend.
breakfast       It's my presiouse time that take a "Japanese "breakfast in the warm sun light.
times           Because Eating Japanese foods takes many times.

--- take / breakfast / A2 (n=73) ---
lot             In the morning, I can't take a lot of breakfast because I wake up so slow.
train           Then I take the train.
bath            I take a bath, wear my school's uniform, and my tooth in the thirty minutes.
time            But, it takes long time, so I have to get up earlier.
time            It takes long time to eat.
time            If, breakfast is rice, I take much time for it.
time            Because it takes little time to eat.
food            We are Japanese, so we have to take Japanese food.
train           I have to leave home at 6:45 to take a train.
time            Because bread doesn't take time to make.
lot             But it takes a lot of time.
lot             Because rice can make my very full without taking a lot of time.
time            Because it takes long time to eat Japanese food.
time            I think eating Japanese food takes much time.
breakfast       I don't like not to take a breakfast.
time            I think It is better to eat breads for break-fast because it takes a little time to eat them.
breakfast       I think that it is bad that taking no breakfast.
breakfast       If you (NO. 1) were to keep to take no breakfast, you would not be healthy.
time            By the way, I want to eat rice better, but it takes rather more time.
minutes         It takes me about ten minutes to have breakfast.
time            I like bread more than rice, for I have to take a long time to eat rice.
bread           She take bread and milk on hte table
bus             If I eat breakfast at my house and I don't take a bus.
bread           One of reasons is I can take bread to the school, and eat it in rest time, bread is very other one is I hardly eat bread at lunch and dinner.
newpaper        If I choose eating rice in the morning, I won't be able to take a newpaper.
lot             Because it takes a lot of minutes to making it.
minutes         It usually takes me about 15 minutes.
time            It is very nice and It doesn't take time.
minutes         it takes 15 minutes to make miso soup.
bread           So it is very to take bread and milk in breakfast.
breakfast       In Japan, many people take breakfast.
times           Bread is prepared easily and eating it don't take times.
breakfast       Every morning I always take a breakfast.
minutes         Not rice and soup I take ten or fifteen minutes to have a breakfast in the morning.
time            That's no problem to me, cause I like, but it takes much time to brush my teeeth.
time            People say it takes time to cook rice cooker I want to sleep.
time            It takes much time to eat rice, because I eat rice Bread and butter is easy to eat.
hour            As I go to my school by train and it takes more than an hour, so I get up early and I don't sometimes have breakfast, but I try to buy some bread on the way to school.
rice            Because I get up late in the morning and I have no time to take rice and something.
rice            I usually have bread and tea, but sometime I take rice and soup snd so on.
time            But it is said that it takes time to cook rise and soup.
bread           But when I want to leave for school as soon as I can, I take bread and milk (or tea).
time            I think that it takes time to cook rice and soup.
time            It takes long time to have rice, so I usually have bread.
muchtime        But it takes muchtime to eat rice and soup.
time            Because it is not take much time to have bread.
times           My mother likes bread than rice, and she says thst it takes many times to cook rice and Japanese meal.
pill            Instead of some bread or salad, I always take the pill which contains vitamin.
time            Because they take only a few time.
time            I don't like these so much but this menu takes little time to cook.
bread           I take bread in the morning, and rice at night.
time            If I took the time to have breakfast as everyday, I would be rate for school.
bas             bUt, sometimes before I take a bas.
time            I can't take time for breakfast.
times           But it takes too many times to me.
bread           I take bread, my mother makes it.
rice            Third, because rice need a lot of time to cook, my parents don't want to take rice to the breakfast.
time            I rarely have rice because it takes more time to eat rice than bread.
classes         I think that if I don't eat luch earlier time I can't take classes seriously.
butter          Bread with butter is not so healthy as rice, for taking butter everyday morning is not good for health.
fat             There are many European and American people who are ill because of taking fat too much.
calory          My parents always say to me if you don't take enough calory, you would feel hungry before lunch and couldn't concetrate on anything.
bread           I take bread in the morning, and rice at night.
lot             Rice and take a lot of times.
lot             But bread and milk don't take a lot of time.
time            Becaus bread is takes time.
foods           For snother thing, can't take foods.
time            I don't take time for breakfast, because the morning is very busy.
time            If I am able to wake up early in morning, I will take more time for breakfast, and eat more than now!
time            I also like rice and miso soup, but it takes a time to eat.
time            It took long time, so math teacher agury.
lot             Because Bread don't take a lot of time to eat.
time            so, our's breakfast is bread and, milk tea, Because, It takes not much time to make them.

--- take / breakfast / B1+ (n=90) ---
breakfast       I take my breakfast in four minutes on school days.
breakfast       So i don't have time to take my breakfast enough.
eggs            I take eggs and at Sunday.
breakfast       I think we must take breakfast.
train           I had miss take the train.
classes         Because if I don't have breakfast, I will not be able to take classes.
breakfast       So I wanna take the breakfast more slowly.
lot             Japanese food take a lot of times, and bread don't take a lot of times.
time            But rice takes too much time.
milk            So I have to take milk.
lot             But my mother said "Japanese food takes a lot of time, I like to make better."
bread           Some times I late get up, so I don't have breakfast or take a bread and go to school.
breakfast       I always take a breakfast.
lot             So, I take a lot of breakfast.
breakfast       But I sometimes can't take a breakfast when I got up late.
brteak          I think, to take a brteak fast is very important.
break           I hope I can take a break fast everyday.
lot             「No, I don't cook Japanese food because it take a lot of times.
times           「OK, By the way how many times do you take to cook lunch? 」
minuts          It takes about 10 minuts.
time            It doesn't take much time.
time            But it takes too much time.
kitkat          I take a few kitkat.
time            Eeating rice takes longer time than bread.
breakfast       I think taking breakfast is the most important.
breakfast       My friend said "Taking breakfast make me fat!"
misstake        But I took a misstake!
minutes         It takes about five minutes to make it.
time            Because eating rice and miso takes a long time.
times           But it takes several times to eat.
times           Bread takes a few times to eat.
minutes         It takes about 10-12 minutes to eat.
minutes         I took about 20 minutes to eat it.
hour            (Exept on Sunday, I usually took 1 hour on Sunday. )
breakfast       I get hungry even when I took a breakfast as usual.
time            Hower, it takes long time, By the way, Do you want to know why I eat breakfast?
break           I always take a break fast in the morning.
rice            I took rice and put it into trash can.
part            Therefor, I can't take part in the club activity in the morning.
breakfast       I can't live without breakfast every day, Sometimes, I sleep over and no time to take breakfast if I get school in time.
breakfast       But, I choose the way to take breakfast and late for school.
breakfast       By the way I think that taking a breakfast is really important for ous selves.
time            I have to take very long time to eat meal, and it is very busy for the students to awakeness to departure, so it always bothers me.
time            I think to eat rise takes longer time than to eat bread.
time            But I eat it in dinner, taking long time with my family.
margarine       She take margarine with bread.
train           I take a train to school for long time.
time            It's not take so long time.
lunch           I have to take lunch.
time            Because it takes too much time to eat rice and miso soup.
time            To have bread for breakfast, it doesn't take so much time.
time            But it takes more time to cook rice in The morning.
time            But in case of rice you muse need MISO soup which is also taken more time to cook, and and so on.
juice           I usually take an orange juice in summer and in spring, and a hot soup in fall and in winter.
bread           I like it, and why not I take bread in the morning. . . because, bread can't full of my stomach.
lot             At first, nice menu take a lot of time to read and to eat up.
breakfast       I prefer to take breakfast for bread, because I like bread very much.
breakfast       But my family take breakfast individually.
time            Not only they take little time but also they have different prefrence.
breakfast       My father and I prefer to to take breakfast for bread, but my mother and my little brother prefer to take breakfast for rice.
cup             I ususally eat eggs, cheese and bread, and take a cup of coffee in final.
breakfast       So, I want to take breakfast in my home."
breakfast       But my mother and my little brother say,"We want to take breakfast in Washoku, because we are Japanese.
minutes         My mother take only ten minutes in preparing the breakfast.
kinds           It is that me can take much callory and many kinds of food.
train           When I take in the train, I feel bad.
uniform         Every morning I wake up at 5:55, wash face, take on uniform, have breakfast, am sent to station by car and get on the 6:27 train.
time            It takes too much time to serve a meal.
minutes         I take about five minutes to eat breakfast on weekday.
shokupan        When I get to the dining table, I take "SHOKUPAN "first.
sugars          Whenever I drink milk tea, I don't take some sugars.
trip            I little eat rice, for exmaple take a trip, friend's house, and so on.
time            But, if rice is saued as a breakfast, it takes me many time to eat it.
bread           Taking bread for breakfast is fast and easy, so my mother often give me bread for breakfast.
time            I leave home early in the morning; so I can't take a long time to eat breakfast.
hour            In fact, I want to eat much more, but I have to go to school early in the morning because it is far from my house and it takes more than a hour to get there.
time            But it takes a long time for me to eat Japanese food, rice, soup and fish.
minutes         I eat bread without baking, so it takes only about five minutes for me to eat it.
bath            I spend the time most happily when I'm taking a bath, travelling by train and when I have much time to leave home in the morning.
time            So it always takes me little time to finish it.
foods           So although I heard that Japanese teenagers tend not to have breakfast, I can't do without breakfast, even if the crisis that I get up 5 minutes before the time I have to leave home happens, I take some foods and eat them.
minutes         It also takes only a few minutes to tost bread.
time            If I can do, I want to have breakfast everyday, and want to take much time to do it.
time            So, I want to have breakfast everyday and want to take much time to do it.
breakfast       I have that there are many people who don't take breakfast.
breakfast       But good to take breakfast better than don't take it.
time            Rice and miso soup take much time.
time            But it takes more time to eat Japanese foods than American's.
amount          I need to take sufficient amount of breakfast to commute by train in such hours.
drink           My father only takes drink as breakfast.

### % of "take time" by topic and CEFR level

In [36]:
# %%
time_sub = raw[(raw['verb']=='take') & (raw['collocate']=='time')]
time_sub.groupby('level')['topic'].value_counts(normalize=True).round(3) * 100

level  topic
A1     breakfast     50.0
       earthquake    50.0
A2     breakfast     93.5
       earthquake     6.5
B1+    breakfast     82.8
       festival      13.8
       earthquake     3.4
Name: proportion, dtype: float64

# "Make"

In [10]:
movers = biggest_movers(noun_df, 'make')
print('Rising toward B1+ (top):')
print(movers.head(top_n=10) if False else movers.head(10))
print('\nReceding toward B1+ (bottom):')
print(movers.tail(10))

Rising toward B1+ (top):
level   A1   A2  B1+  delta_A1_A2  delta_A2_B1  delta_A1_B1
noun
house  0.6  3.2  2.6          2.6         -0.6          2.0
movie  1.8  5.8  3.7          4.0         -2.1          1.9
gate   0.0  0.5  0.8          0.5          0.3          0.8
thing  0.0  0.6  0.8          0.6          0.2          0.8
art    0.0  0.3  0.8          0.3          0.5          0.8
lunch  0.3  0.5  1.0          0.2          0.5          0.7
a.     0.3  0.4  0.9          0.1          0.5          0.6
cakes  0.0  0.2  0.6          0.2          0.4          0.6
goal   0.0  0.3  0.6          0.3          0.3          0.6
mind   0.0  0.5  0.6          0.5          0.1          0.6

Receding toward B1+ (bottom):
level         A1   A2  B1+  delta_A1_A2  delta_A2_B1  delta_A1_B1
noun
pool         0.6  0.0  0.0         -0.6          0.0         -0.6
udon         0.6  0.2  0.0         -0.4         -0.2         -0.6
vegitaveles  0.6  0.0  0.0         -0.6          0.0         -0.6
whitehouse   0.6  0.0  0.0         -0.6          0.0         -0.6
time         0.9  0.4  0.3         -0.5         -0.1         -0.6
story        1.2  0.7  0.3         -0.5         -0.4         -0.9
foods        1.2  0.6  0.3         -0.6         -0.3         -0.9
bridge       0.9  0.2  0.0         -0.7         -0.2         -0.9
mother       0.9  0.3  0.0         -0.6         -0.3         -0.9
rice         1.5  0.5  0.3         -1.0         -0.2         -1.2

In [40]:
# examples of make house A2
raw[(raw['verb']=='make') & (raw['level']=='A2') & (raw['collocate']=='house')]['sentence'].sample(30, random_state=42).to_list()

['In our school festival, we made a ghost house.',
 'our class make ghost house.',
 'In the school festival, our class made a ghost house.',
 'This year, our class made a fantom-house.',
 'But we could complete making a Japanese haunted house by the time.',
 "In my friend's class, they have made house for long time.",
 'Our class cooprated to make a ghost house for about two weeks before the festival.',
 'I was willing to make our special "gost house ".',
 'Our class made a "PHOTO HOUSE ".',
 'Our class made a ghost house.',
 'Our class made a ghost house.',
 'We made a Ghost House in classroom.',
 'Our class made the ghost house.',
 'Because it was dicided that we have to done about art, but we made a ghost-house of Egypt.',
 "As I belong to vollyball club, I couldn't help to make the ghost house so often, but I helped to make the ghost as much as I could.",
 'That is why, we wanted to make ghost house or foods.',
 'Our class make a old house.',
 "This year, our class didn't allow to make a goast house.",
 'Our class made a "Ghost house "on school festival.',
 'Our class made a ghost house.',
 'Our class made a big house.',
 'Our class had make ghost house.',
 'I tried very hard to make this house.',
 'My house is not made from wood.',
 'After many hours, he understood and decided to make his new house first of all.',
 'Our class made a horror house.',
 'He make a house.',
 'Our class made goast house.',
 'Our class made picture house.',
 'One of this rule is that only some classes can make a goast house.']

In [57]:
# # %%
# raw[(raw['verb']=='make') & (raw['level']=='A2') & (raw['collocate']=='house')]['topic'].value_counts()

# %%
raw[(raw['verb']=='make') & (raw['collocate']=='house')]['topic'].value_counts()

topic
festival      56
urashima       5
earthquake     2
Name: count, dtype: int64

In [42]:
# examples of make movie A2
raw[(raw['verb']=='make') & (raw['level']=='A2') & (raw['collocate']=='movie')]['sentence'].sample(10, random_state=42).to_list()

['We made a movie for the school festival.',
 'Our class made a movie this year.',
 'This year, we made a movie.',
 'Our class made a movie for a school festival.',
 'This year, our class made a movie.',
 'This year our class made movie.',
 'Our class made a movie named "The festival of death ".',
 'Our class made a movie.',
 'I made movie last and one more last year.',
 'Because it is not interesting for me to make a movie.']

In [56]:
# # %%
# raw[(raw['verb']=='make') & (raw['level']=='A2') & (raw['collocate']=='house')]['topic'].value_counts()

# %%
raw[(raw['verb']=='make') & (raw['collocate']=='house')]['topic'].value_counts()

topic
festival      56
urashima       5
earthquake     2
Name: count, dtype: int64

In [50]:
# examples of make rice A1
raw[(raw['verb']=='make') & (raw['level']=='A1') & (raw['collocate']=='rice')]['sentence'].sample(5, random_state=42).to_list()

['So he wants to make rice.',
 'He make rice and vegitaveles.',
 'He made "Great rice".',
 'I can make rice and.',
 'He make rice and vegitaveles.']

# "Make" clausal

In [51]:
# %%
df[(df['verb']=='make') & (df['category']=='clausal')][['level', 'n', 'total', 'pct']]

   level    n  total   pct
28    A1   56    327  17.1
36    A2  293   1128  26.0
46   B1+  226    930  24.3

In [53]:
# %%
for lvl in ['A1', 'A2', 'B1+']:
    sub = raw[(raw['verb']=='make') & (raw['category']=='clausal') & (raw['level']==lvl)]
    print(f'--- make / clausal / {lvl} (n={len(sub)}) ---')
    for s in sub['sentence'].sample(min(12, len(sub)), random_state=1):
        print(s)
    print()

--- make / clausal / A1 (n=56) ---
And I like American pop music, walk-man makes me happy.
He made lost.
And his son grew up to go to kill He waked and he make His name is Momotaro.
Milk makes me strong.
Making them moved by ourselves was the happiest thing: Also, everyone in my class, this was a big too.
Although our class made funny sceans sometime, probabory, it was serious.
There are many programs, I make, in the disks.
Many make the room bright! fin
If you go there, it makes you feel to want to go Okinawa.
I make it rule to read newspaper having breakfast.
I, it make me sad. . .
make is use making.

--- make / clausal / A2 (n=293) ---
Their smile and beautiful mind make me happy.
But, after all it makes my condision bad.
And we make effect to make good things.
But Rice and makes me warm.
It makes me hungry in the mornings, but I msut bear to eat a lunch at an early hour.
And milk makes me tall.
It made me happy.
Baking them well made me so happy.
Make the movie is very difficult.
The water made him young.
Our ghost house made a lot of people scaried anf enjoyed.
The which my mother made me last Febrary.

--- make / clausal / B1+ (n=226) ---
so Japan tuaer sistem made the trip to see the sterwars so.
He tried to make her notice him again and again, and she thought Urashim was lost and might be dead, so she didn't believe him.
Music makes me feel confortable and relaxed.
We make wait.
Bread has a lot of butter in it, and that makes me feel bad after eating bread.
I don't know what makes us so lazy.
Their songs give me power and make me happy.
This type dream makes me tired.
that made me busy more.
Fish has less fast compared to meat and it contains DHA which make our brain more intelligent.
but, my friends made it well.
King make him his surbant.

# "like"

In [15]:
movers = biggest_movers(noun_df, 'like')
print('Rising toward B1+ (top):')
print(movers.head(top_n=10) if False else movers.head(10))
print('\nReceding toward B1+ (bottom):')
print(movers.tail(10))

Rising toward B1+ (top):
level        A1    A2   B1+  delta_A1_A2  delta_A2_B1  delta_A1_B1
noun
bread      10.7  12.5  13.1          1.8          0.6          2.4
festival    1.5   2.3   3.9          0.8          1.6          2.4
tea         0.7   0.8   1.3          0.1          0.5          0.6
foods       0.2   0.5   0.6          0.3          0.1          0.4
natto       0.0   0.5   0.2          0.5         -0.3          0.2
soup        0.5   1.9   0.7          1.4         -1.2          0.2
food        1.1   1.6   1.3          0.5         -0.3          0.2
breakfast   0.6   1.2   0.6          0.6         -0.6          0.0
coffee      0.2   0.5   0.1          0.3         -0.4         -0.1
song        0.4   0.7   0.2          0.3         -0.5         -0.2

Receding toward B1+ (bottom):
level         A1    A2   B1+  delta_A1_A2  delta_A2_B1  delta_A1_B1
noun
basketball   0.4   0.5   0.0          0.1         -0.5         -0.4
egg          0.8   0.3   0.4         -0.5          0.1         -0.4
music        2.3   2.8   1.8          0.5         -1.0         -0.5
fish         0.7   0.3   0.1         -0.4         -0.2         -0.6
books        1.1   0.8   0.3         -0.3         -0.5         -0.8
tennis       1.2   0.4   0.3         -0.8         -0.1         -0.9
game         1.0   0.4   0.0         -0.6         -0.4         -1.0
rice        12.0  12.1  10.9          0.1         -1.2         -1.1
soccer       1.2   0.6   0.0         -0.6         -0.6         -1.2
milk         4.7   4.7   2.3          0.0         -2.4         -2.4

# "like" + infinitive

In [54]:
# %%
df[(df['verb']=='like') & (df['category']=='infinitive')][['level', 'n', 'total', 'pct']]

   level    n  total   pct
4     A1   44   1183   3.7
11    A2  158   1982   8.0
20   B1+  108    991  10.9

In [16]:
# %%
for lvl in ['A1', 'A2', 'B1+']:
    sub = raw[(raw['verb']=='like') & (raw['category']=='infinitive') & (raw['level']==lvl)]
    print(f'--- like / infinitive / {lvl} (n={len(sub)}) ---')
    for s in sub['sentence'].sample(min(8, len(sub)), random_state=1):
        print(s)
    print()

--- like / infinitive / A1 (n=44) ---
I like to take pictures.
I would like to listen to music everytime and everywhere because I will do.
I like to eat buying.
I like to sleep very much.
I likes to use my computer.
I would like to buy clothes with next year's.
I don't like to do."
It said "I'd like to invite Ryuguujo!"

--- like / infinitive / A2 (n=158) ---
Because I like to listen to music.
So, I'd like to bring money first.
I like to listen to music.
I like to read newspaper when I was having breakfast.
I like to eat bread on breakfast.
And I like to read books and comics.
At first, I didn't like to do my.
I like to play a sports game.

--- like / infinitive / B1+ (n=108) ---
And I like to read books very much.
I like to eat rice in the night and noon.
I like to eat.
Because I think I don't like to eat rice in the morning.
After all, I don't like to use a big money.
But I think foreigner may say that he or she likes to eat bread for breakfast.
These pictures are really my treasures, so I'd like to bring my albums.
I like to listen music so I have many CDs.

In [17]:
# %%
verbal_df = pd.read_excel('extract_constructions.xlsx', sheet_name='verbal_complements')

def biggest_movers_verbal(verbal_df, verb, category, top_n=15, min_pct=0.3):
    sub = verbal_df[(verbal_df['verb'] == verb) & (verbal_df['category'] == category)]
    wide = sub.pivot_table(index='complement', columns='level',
                            values='pct_of_sentences', fill_value=0)
    wide = wide.reindex(columns=['A1', 'A2', 'B1+'], fill_value=0)
    # ignore complements too rare to be worth reading into either way
    wide = wide[wide.max(axis=1) >= min_pct]
    wide['delta_A1_A2'] = wide['A2'] - wide['A1']
    wide['delta_A2_B1'] = wide['B1+'] - wide['A2']
    wide['delta_A1_B1'] = wide['B1+'] - wide['A1']
    return wide.sort_values('delta_A1_B1', ascending=False)

# %%
movers = biggest_movers_verbal(verbal_df, 'like', 'infinitive')
print('Rising toward B1+ (top):')
print(movers.head(10))
print('\nReceding toward B1+ (bottom):')
print(movers.tail(10))

Rising toward B1+ (top):
level        A1   A2  B1+  delta_A1_A2  delta_A2_B1  delta_A1_B1
complement
eat         0.6  2.6  3.3          2.0          0.7          2.7
listen      0.3  0.6  1.0          0.3          0.4          0.7
be          0.0  0.2  0.4          0.2          0.2          0.4
see         0.0  0.1  0.4          0.1          0.3          0.4
take        0.2  0.2  0.6          0.0          0.4          0.4
bring       0.0  0.1  0.3          0.1          0.2          0.3
carry       0.0  0.0  0.3          0.0          0.3          0.3
go          0.2  0.3  0.4          0.1          0.1          0.2
sing        0.3  0.0  0.5         -0.3          0.5          0.2
read        0.1  0.3  0.3          0.2          0.0          0.2

Receding toward B1+ (bottom):
level        A1   A2  B1+  delta_A1_A2  delta_A2_B1  delta_A1_B1
complement
be          0.0  0.2  0.4          0.2          0.2          0.4
see         0.0  0.1  0.4          0.1          0.3          0.4
take        0.2  0.2  0.6          0.0          0.4          0.4
bring       0.0  0.1  0.3          0.1          0.2          0.3
carry       0.0  0.0  0.3          0.0          0.3          0.3
go          0.2  0.3  0.4          0.1          0.1          0.2
sing        0.3  0.0  0.5         -0.3          0.5          0.2
read        0.1  0.3  0.3          0.2          0.0          0.2
have        0.2  0.7  0.2          0.5         -0.5          0.0
play        0.4  1.0  0.3          0.6         -0.7         -0.1

In [60]:
# %%
raw[(raw['verb']=='like') & (raw['category']=='infinitive') & (raw['collocate']=='eat')].groupby('level').size()

# %%
for lvl in ['A1', 'A2', 'B1+']:
    sub = raw[(raw['verb']=='like') & (raw['category']=='infinitive') & (raw['collocate']=='eat') & (raw['level']==lvl)]
    print(f'--- like to eat / {lvl} (n={len(sub)}) ---')
    for s in sub['sentence'].sample(min(52, len(sub)), random_state=1):
        print(s)
    print()

--- like to eat / A1 (n=7) ---
I like to eat rice in the breakfast.
But, I like to eat
I don't like to eat rice.
Because I don't like to eat bread in the morning.
But I don't eat too much and I don't like to eat meat, because I don't like very much.
I like to eat.
I like to eat buying.

--- like to eat / A2 (n=52) ---
I like to eat rice more than bread in breakfast.
Sometimes I don't like eat lunch
I like to eat them in the morning and have no complaint about it.
And I like to eat delicious food.
But, I don't like to eat at morning.
I don't like to eat bread in the morning.
I like to eat shokupan with ham.
I don't have Natoo, but I wouldn't like to eat it in the morning.
I like to eat them, too.
If there is a ham or with bread, I like to eat bread for breakfast.
I like to eat fried fish and Sashimi.
I like to eat bread in the morning.
because, I like very to eat.
But I don't like to eat rice in the morning.
I like to eat.
I'd like to eat rice rather than bread.
I like to eat but I can't eat anything every morning.
I like to eat bread at breakfast.
I like to eat bread on breakfast.
Of course, I like to eat bread sometimes.
Because my mother doesn't like to eat bread in the morning.
I like to eat bread.
I don't like to eat rice in breakfast.
I'd like to eat bread in morning.
I like to eat sandwiches the most.
In the morning, I like to eat bread better than rice.
I don't like to eat rice in morning, because I feel rice of moring is not delicious.
I like to eat meal.
I don't like to eat rice and -soup in the morning, because they make make my stomach heavily.
I would like to eat rice in morning, because my parents have done so.
Because I like to eat.
And I like to eat bread by nature.
I like to eat rice with and tea.
So I would like to eat rice tomorrow morning.
My Parents like to eat bread, and I must eat breads.
I like to eat rice for breakfast.
I'd like to eat rice in the morning.
Especialy, I like to eat rice and soy-soup and baked fish.
I don't like to eat much rice in the morning.
But I would like to eat breakfast every morning.
I don't know why I don't like to eat it in the mornig.
I like to eat breakfast.
But I don't like to eat it.
I like to eat it with
My morning time is always busy, so I like to eat them only in the morning.
I am fat a little because I like to eat.
I'd like to eat Japanese food, but I have no time.
I like to eat fish very much.
I like to eat rice with some very much.
I like to eat sweet foods.
But It doesn't mean that I don't like to eat rice and soup in the morning.
Otherwise, sometimes I feel liking to eat rice, such as' ' or' '.

--- like to eat / B1+ (n=33) ---
But I think foreigner may say that he or she likes to eat bread for breakfast.
Many of people like to eat for breakfast.
I like to eat bread with storovery jum.
Because I think I don't like to eat rice in the morning.
I don't like to eat rice in the morning, so I have eaten rice in the morning under ten times.
I like to eat Okayu for breakfast.
I like to eat rice better.
So I like to eat bread for breakfast.
I like to eat bread for breakfast.
I like to eat.
European would like to eat bread.
But at a morning I would like to eat rice.
Most of Japanese people like to eat chocolate-banana at the festival.
I don't like to eat bread and milk.
I like to eat rice for breakfast.
On such a day, I would like to eat bread and drink a cup of tea.
I like to eat those kind of bread with jam, and I like strawbery the most.
But I don't like to eat rice in the morning.
I like to eat rice in the night and noon.
I like to eat rice with "otukemono "and "ochazuke ".
Bread can prepare faster than rice, but I like to eat rice.
I like to eat something sweet after break fast very much.
Usually I eat bread for breakfast because my mother likes to eat bread.
What I'd like to eat is different day by day.
I like to eat bread with blueberry jam.
Really, I would like to eat rice, because my family like to eat rice.
I like to eat fruits.
I like to eat bread with sala bread with egg, bread with strawberry, etc etc. . .
I like to eat rice.
So I would like to eat breakfast in the train.
So, I like to eat both bread and rice.
I like to eat rice, too.
I like to eat salmon with rice.

In [59]:
# %%
raw[(raw['verb']=='like')  & (raw['category']=='infinitive') & (raw['collocate']=='eat')]['topic'].value_counts()

topic
breakfast     87
earthquake     4
festival       1
Name: count, dtype: int64

# HD-D

In [78]:
# %%
from lexicalrichness import LexicalRichness

def hdd_table(raw_df, verb, collocate_categories=('noun', 'proper_noun')):
    sub = raw_df[(raw_df['verb'] == verb) &
                 raw_df['category'].isin(collocate_categories) &
                 raw_df['collocate'].notna()]
    by_level = {lvl: sub[sub['level'] == lvl]['collocate'].tolist()
                for lvl in ['A1', 'A2', 'B1+']}
    draws = min(len(v) for v in by_level.values())
    rows = []
    for lvl in ['A1', 'A2', 'B1+']:
        colls = by_level[lvl]
        lex = LexicalRichness(' '.join(colls))
        hdd_score = lex.hdd(draws=draws)
        rows.append({'level': lvl, 'n_tokens': len(colls),
                     f'HD-D (draws={draws})': round(hdd_score, 4),
                     'expected_types': round(hdd_score * draws, 2)})
    return pd.DataFrame(rows).set_index('level')

# %%
# hdd_table(raw, 'like') # including proper nouns
hdd_table(raw, 'like', collocate_categories=('noun',))       # nouns only

       n_tokens  HD-D (draws=521)  expected_types
level
A1          631            0.2599          135.43
A2         1073            0.2563          133.55
B1+         521            0.2894          150.80

In [73]:
# hdd_table(raw, 'take')
hdd_table(raw, 'take', collocate_categories=('noun',))       # nouns only

       n_tokens  HD-D (draws=198)  expected_types
level
A1          198            0.4596           91.00
A2          652            0.4544           89.98
B1+         640            0.4908           97.17

In [76]:
# hdd_table(raw, 'make')
hdd_table(raw, 'make', collocate_categories=('noun',))       # nouns only

       n_tokens  HD-D (draws=137)  expected_types
level
A1          137            0.6715           92.00
A2          502            0.6110           83.70
B1+         431            0.6440           88.22

# check "make" collocates

In [88]:
# %%
counts = raw[(raw['verb']=='make') & (raw['category']=='noun')]['collocate'].value_counts()
for noun, n in counts.items():
    print(f'{noun:15s} {n}')

movie           105
house           56
breakfast       43
friends         22
bread           22
festival        19
lot             18
story           15
lunch           14
rice            14
thing           14
a.              14
gate            13
foods           13
stage           12
mind            12
friend          11
food            11
money           10
art             10
film            9
time            9
memory          8
things          8
play            8
plan            8
goal            8
effort          8
cake            7
picture         6
game            6
mistake         6
memories        6
fire            6
mother          6
sound           5
events          5
book            5
programs        5
records         5
doughnut        5
break           5
bridge          5
cloth           5
stories         5
box             5
cakes           5
people          5
soup            4
group           4
fun             4
power           4
kind            4
movies          4
sandwiches      4
sweets          4
success         4
building        4
kinds           4
room            4
good            3
report          3
class           3
juice           3
shirt           3
drama           3
posters         3
door            3
reports         3
wall            3
music           3
way             3
mistakes        3
line            3
groups          3
living          2
exhibition      2
cinema          2
piza            2
gus             2
friendship      2
songs           2
doughnuts       2
dance           2
inside          2
face            2
traps           2
works           2
coffee          2
bords           2
capital         2
record          2
decoration      2
plays           2
son             2
day             2
museum          2
ice             2
bands           2
banana          2
decorations     2
ship            2
machine         2
walls           2
games           2
films           2
dramas          2
potion          2
place           2
display         2
point           2
dinner          2
shows           2
dream           2
cocoa           2
ling            2
work            2
song            2
sandwich        2
tea             2
students        2
set             2
man             2
key             2
preparation     2
smile           2
plane           2
efforts         2
lots            2
band            2
space           2
data            1
bom             1
documents       1
plogram         1
cooking         1
notebook        1
drag            1
trap            1
presentation    1
queu            1
wife            1
pepor           1
classroom       1
dangoes         1
snowman         1
lunches         1
stone           1
misemono        1
love            1
round           1
lof             1
color           1
someting        1
jerry           1
doll            1
anvalance       1
lion            1
plans           1
tour            1
pyramid         1
knowledge       1
relationship    1
bunch           1
youold          1
energy          1
breakfst        1
everytime       1
morning         1
vase            1
vacation        1
revorusion      1
mans            1
bugs            1
s.              1
theattraction   1
taste           1
window          1
woman           1
pizza           1
classmate       1
idea            1
breslets        1
name            1
fruits          1
worm            1
appearance      1
festivals       1
remembrance     1
research        1
dress           1
pet             1
bicycle         1
hotdog          1
salada          1
homepage        1
cook            1
variery         1
bag             1
cooks           1
shut            1
welcome         1
ochazuke        1
gaft            1
ranking         1
enjoy           1
s               1
mess            1
noise           1
srories         1
distance        1
napzack         1
water           1
parl            1
dounuts         1
nest            1
bath            1
tools           1
exhilition      1
sauna           1
t-              1
noun            1
sandwitches     1
efort           1
sofa            1
deserts         1
ticket          1
progress        1
hair            1
clothing        1
pieces          1
daunut          1
timetable       1
objects         1
rode            1
closes          1
tickets         1
case            1
preparations    1
crowd           1
flower          1
electricity     1
drink           1
show            1
river           1
nonsence        1
gosttown        1
restrant        1
types           1
pecchar         1
contest         1
rise            1
software        1
mantion         1
breadfarst      1
life            1
dolls           1
trip            1
father          1
map             1
get             1
videos          1
boards          1
boat            1
omisoshilu      1
care            1
children        1
world           1
characters      1
chance          1
angel           1
history         1
crime           1
riceball        1
hands           1
move            1
prepare         1
sinema          1
pictuer         1
hospital        1
light           1
questions       1
whitehouse      1
question        1
quetion         1
coners          1
coner           1
piy             1
potato          1
farst           1
dinnir          1
meet            1
model           1
parper          1
stars           1
vegetable       1
zoo             1
muchin          1
graph           1
bady            1
hamster         1
misstake        1
medchine        1
timemachine     1
magazine        1
background      1
picuture        1
desert          1
bananas         1
cookies         1
feeling         1
sets            1
theater         1
girls           1
rest            1
paint           1
member          1
equipments      1
panfret         1
cottage         1
hypothesis      1
body            1
type            1
balune          1
trouble         1
groupes         1
udon            1
shirts          1
submarin        1
drug            1
goods           1
connection      1
call            1
albums          1
notes           1
number          1
ring            1
size            1
poster          1
atraction       1
performance     1
brother         1
conversation    1
efforte         1
donuts          1
ground          1
looks           1
ghost           1
ghosthouse      1
panflets        1
course          1
fiends          1
schedule        1
savings         1
robot           1
promise         1
city            1
ideas           1
joke            1
statement       1
submaline       1
breads          1
rices           1
concert         1
post            1
net             1
target          1
hoop            1
goals           1
spot            1
got             1
keybord         1
beauty          1
sounds          1

In [91]:
# %%
make_nouns = raw[(raw['verb']=='make') & (raw['category']=='noun')]

for lvl in ['A1', 'A2', 'B1+']:
    print(f'--- make / noun / {lvl} ---')
    counts = make_nouns[make_nouns['level']==lvl]['collocate'].value_counts()
    for noun, n in counts.head(15).items():
        print(f'{noun:15s} {n}')
    print()

--- make / noun / A1 ---
movie           6
breakfast       6
festival        5
bread           5
rice            5
story           4
foods           4
time            3
lot             3
bridge          3
mother          3
mistake         2
memory          2
building        2
play            2

--- make / noun / A2 ---
movie           65
house           32
breakfast       22
friends         10
story           8
stage           8
lot             7
thing           7
bread           7
mind            6
festival        6
money           6
foods           6
rice            6
food            6

--- make / noun / B1+ ---
movie           34
house           22
breakfast       15
friends         10
bread           10
lunch           8
festival        8
lot             8
a.              8
thing           7
gate            7
art             7
mind            6
friend          5
doughnut        5